// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pymgvmqezoucjiaglgec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bWd2bXFlem91Y2ppYWdsZ2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTIwNjQsImV4cCI6MjA3Mzg2ODA2NH0.GXpxVnmBX0623F4Dt3geuVDmeKyE1au3c4yzjk9gXjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);